### ISSUE TITLE
Number of attempts

### ISSUE THREAD

**Issue by IanaKhitsko** [MVitalina/EuroDiffusion#2]
https://github.com/MVitalina/EuroDiffusion/blob/34f1b020389972bf7c1badf3289f30c36b6884d5/Program.cs#L19

100 is a number of characters? I think this is not too much to process at least 4 cases with several countries

**Comment by MVitalina** [comment]
It`s a number of attempts to get info from a user. We don`t need to have an endless cycle.
Constants instead of magic numbers are added
