### ISSUE TITLE
Array.Every

### ISSUE THREAD

**Issue by IanaKhitsko** [MVitalina/EuroDiffusion#3]
https://github.com/MVitalina/EuroDiffusion/blob/34f1b020389972bf7c1badf3289f30c36b6884d5/Entities/Town.cs#L38

Can we use smth like this:  Coins.Where(x => x > 0).Every();  ? (I'm not a c# dev). Is so, will we loose in performance?

**Comment by MVitalina** [comment]
Done
`Coins.All(x => x > 0);`
