### ISSUE TITLE
Motif == 0

### ISSUE THREAD

**Issue by IanaKhitsko** [MVitalina/EuroDiffusion#6]
https://github.com/MVitalina/EuroDiffusion/blob/34f1b020389972bf7c1badf3289f30c36b6884d5/Entities/Country.cs#L37

What if Motif == 0 in this case?

**Comment by MVitalina** [comment]
![image](https://user-images.githubusercontent.com/25820970/102283653-7bf1da00-3f3b-11eb-8929-26b3283900ae.png)
It can be because it smth like "id"
