### ISSUE TITLE
"More linear" code style

### ISSUE THREAD

**Issue by IanaKhitsko** [MVitalina/EuroDiffusion#7]
https://github.com/MVitalina/EuroDiffusion/blob/34f1b020389972bf7c1badf3289f30c36b6884d5/MainLogic/Diffuser.cs#L55-L63

Try to write code in more linear style. E.g. : 

                        if (Towns[x, y] != null)
                        {
                             WriteFatalError("Logical error: can`t set Town again.");
                             return false;            
                        }                
                       Towns[x, y] = new Town(new Point(x, y), country, NumberOfCountries);
Thus you'll have 5 lines instead of 9.

**Comment by MVitalina** [comment]
Done
